version = 0.1
[default.deploy.parameters]
stack_name = "sam-cloud-resume-3"
resolve_s3 = true
s3_prefix = "sam-cloud-resume-3"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
