AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Backend for site view counter

Globals:
  #https://github.com/awslabs/serverless-application-model/blob/develop/docs/globals.rst
  Function:
    Runtime: python3.9
    MemorySize: 128
     
Resources:
  ResumeFunction5:
    Type: 'AWS::Serverless::Function'
    Properties:
      
      FunctionName: ResumeFunction5
      CodeUri: ./functions
      Handler: lambda_function.lambda_handler
      Description: Backend for site view counter
      Timeout: 3
      Policies:
      - DynamoDBCrudPolicy:
          TableName: 
            Ref: CounterTable7
        # Give the Lambda service access to poll your DynamoDB Stream
      - AmazonDynamoDBFullAccess
      Events:
        ResumeViews:
          Type: Api
          Properties:
            RestApiId:
              Ref: CloudResumeViewCountApi
            Path: /counter
            Method: get
    Metadata:
      SamResourceId: ResumeFunction5
            
  CloudResumeViewCountApi:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowMethods: "'GET'"
        AllowOrigin: "'www.cloud.ericnbello.com'"
      EndpointConfiguration: Regional
      OpenApiVersion: 3.0.1
      StageName: Prod
      
  CounterTable7:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: siteviews
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: siteviews
          KeyType: HASH
      TableName: countertable7
    
    # Metadata:
    #   BuildMethod: esbuild
    #   BuildProperties:
    #     Minify: true
    #     Target: "es2020"
    #     Sourcemap: true,
    #     EntryPoints: 
    #     - page.tsx